# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rentalproduct_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalproduct',
            name='purchase_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
