# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20160220_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualproduct',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
