# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20160222_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
    ]
